name: Pull request demo
run-name: ${{ github.actor }} is testing now
on: 
  pull_request:
    types: [opened, reopend]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run:  echo pull-request opened